// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmvgjabmtiuotdifdcqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdmdqYWJtdGl1b3RkaWZkY3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTUxNTAsImV4cCI6MjA3MzE5MTE1MH0.bdPolNAlQVBqlS_xTXRdrW04qXtPIXTcbnyJc2uXo0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});